"""API1:2023 - Broken Object Level Authorization (BOLA).

Requires TWO identities (`--auth-header` + `--auth-header-b`), since BOLA is
inherently a cross-user question: "can identity B reach an object identity A
can reach?" With only one identity there's nothing to compare against, so this
check silently skips (returns []) when `ctx.session_b` is not configured.

ALGORITHM (heuristic — read the limitation below before trusting a finding):
1. Only applies to GET endpoints with an id-like path parameter, e.g.
   `/orders/{id}`. Read-only, deliberately: see `write_bola.py` for the
   PATCH/PUT write-based extension (CRITICAL severity, since a write is
   worse than a read) — a separate check, not folded into this one, same
   pattern as excessive_data_exposure.py / mass_assignment.py sharing an
   OWASP id via distinct titles.
2. For a small set of candidate ids, request the endpoint AS USER A. The first
   candidate that returns 2xx is treated as "a real, A-accessible resource" —
   this sidesteps the classic false-negative of guessing an id that doesn't
   exist at all (a 404 there tells you nothing about authorization).
3. Request that SAME id AS USER B. If B also gets 2xx, that's the finding:
   two independently-authenticated identities can both reach the same object.

LIMITATION (be upfront about this — it's a heuristic, not a proof): the check
has no ground truth for who is *supposed* to own the resource. "Two users can
both read this" looks identical from the outside whether the resource is
illegitimately leaked OR legitimately shared/public — real BOLA scanners have
the same limitation without domain knowledge of the target API. Treat a
finding as "worth a human review", not an automatic proof of a bug. (A 403 for
user B is NOT flagged: that's authorization working correctly, distinct from
a 404 — wrong id guess — which the check also doesn't flag.)

Two mitigations for the "legitimately public" false-positive class, each
closing a DIFFERENT flavor of it:

  1. SPEC-DECLARED public endpoints: if the OpenAPI spec explicitly marks an
     operation `security: []` (no auth required at all — a real, standard
     OpenAPI signal, distinct from the spec simply saying nothing about auth;
     see spec_loader.Endpoint.security), skip it. "Two people can read a page
     that needs no login" isn't a finding.
  2. Endpoints that DO require auth but are intentionally shared with every
     authenticated user (e.g. a public announcement) have no such signal in
     OpenAPI — there's no schema construct for "no per-object ownership
     applies here". That can't be inferred from behavior (the response is
     identical either way), so it's closed the same way secret scanners close
     unavoidable false positives: a human-maintained allowlist
     (`ctx.public_paths`, wired from `--public-paths`), not detection.

FOLLOW-UP, done: write-based BOLA (PATCH/PUT another user's object -- DELETE
deliberately excluded, see write_bola.py's own SCOPE section for why).

ID DISCOVERY (added after external validation, see below): before falling
back to `_CANDIDATE_IDS` guessing, tries `discover_resource_id()`
(checks/base.py) -- create a real resource via a sibling POST on this
endpoint's collection path, read the real id back from the response. This
closes the gap for SERVER-GENERATED ids (auto-increment integers, nanoids)
of any shape, not just sequential integers. It does NOT help when the
resource's identifier is something the CLIENT chose at creation time (e.g.
a username you picked during registration) rather than something the
server generates and returns -- there's nothing in the create response to
extract in that case. See the VAmPI result below for exactly this
distinction playing out.

CONFIRMED COST, then CONFIRMED FIX, on VAmPI (github.com/erev0s/VAmPI, see
EXTERNAL_VALIDATION.md target 1 #4b): VAmPI keys users by username, not a
server-generated id, so `["1".."5"]` guessing never found an accessible
resource -- and `PUT /users/v1/{username}/password` has no ownership check
at all, letting one user take over another's account. Manually confirmed
exploitable. Id discovery does NOT close this gap: VAmPI's
`POST /users/v1/register` response is `{"message": "...", "status": "..."}`
-- no id field at all, because the identifier (username) was chosen by the
caller, not generated by the server. Re-verified after adding discovery:
VAmPI's scan result was unchanged at the time.

FIXED for the "my own resource, someone else has a copy of it too" shape
(the exact shape this bug is): `_candidate_ids_for()` now also tries the
scanning identity's OWN username/id, decoded straight out of its own JWT
(`_identity_from_session()`, checks/base.py -- most JWTs carry it as a
plaintext `sub` or `username` claim). Not a guess: the scanning identity
definitely has this exact id, because it's the account that logged in and
got the token. Re-verified live on VAmPI: `GET /users/v1/{username}` now
correctly reports a real BOLA using the scanning identity's own username
as the id -- the same fix that finally let `write_bola.py` catch the
account-takeover bug above. See `_identity_from_session()`'s own
docstring for the honest limit: this only recovers the scanning identity's
OWN id, not an arbitrary other resource's.

WORKING as intended, confirmed against OWASP crAPI (github.com/OWASP/crAPI,
see EXTERNAL_VALIDATION.md target 2 #2): with real, sequential-integer
order ids (crAPI's `POST /workshop/api/shop/orders` returns them), this
check correctly found and reported a real BOLA -- user B reading user A's
complete order, including masked payment card details -- with zero
target-specific code.

ID DISCOVERY CONFIRMED WORKING, also on crAPI: after adding
`discover_resource_id()`, a re-scan found a SECOND, previously-invisible
BOLA on `GET /community/api/v2/community/posts/{postId}` -- discovery
created a real post via `POST /community/api/v2/community/posts` and
extracted its real, non-numeric, nanoid-style id (e.g.
`"6gfDwUFSkXWx255aTjireV"`) from the response, something `["1".."5"]`
guessing could never have found regardless of how many candidates it
tried. Also confirmed discovery reaching an order id (9) past the old
guess range on a live, already-used database -- proving the deeper value
of discovery over merely widening the guess range: a live database drifts,
discovery doesn't need to guess how far.
"""

from __future__ import annotations

import requests

from apisec.checks.base import (
    Finding,
    ScanContext,
    Severity,
    _candidate_ids_for,
    _matches_public_path,
    concrete_url,
)
from apisec.spec_loader import Endpoint


class BolaCheck:
    id = "API1:2023"
    title = "Broken Object Level Authorization (BOLA)"

    def run(self, endpoint: Endpoint, ctx: ScanContext) -> list[Finding]:
        if endpoint.method != "GET":
            return []
        if not _has_id_path_param(endpoint.path):
            return []
        if ctx.session_b is None:
            return []  # can't test cross-user access with only one identity
        if endpoint.security == []:
            return []  # spec explicitly declares this endpoint needs no auth
        if _matches_public_path(endpoint.path, ctx.public_paths):
            return []  # operator has declared this path intentionally shared

        for candidate_id in _candidate_ids_for(endpoint, ctx):
            url = concrete_url(endpoint.path, ctx.base_url, candidate_id)

            try:
                resp_a = ctx.session_a.get(url, timeout=5)
            except requests.RequestException:
                continue
            if resp_a.status_code >= 300:
                continue  # not a real/accessible resource for A; try the next id

            try:
                resp_b = ctx.session_b.get(url, timeout=5)
            except requests.RequestException:
                continue
            if resp_b.status_code < 300:
                return [
                    Finding(
                        check_id=self.id,
                        title=self.title,
                        severity=Severity.HIGH,
                        endpoint=endpoint.path,
                        method=endpoint.method,
                        description=(
                            "Two independently-authenticated identities could both "
                            "access the same object id, with no apparent ownership "
                            "check. If this resource isn't meant to be shared, this "
                            "is a BOLA — user B is reading data that belongs to "
                            "user A. (Heuristic: legitimately shared/public "
                            "resources will also trigger this — treat as a lead to "
                            "verify, not a proof.)"
                        ),
                        evidence=(
                            f"id={candidate_id}: user A got HTTP {resp_a.status_code}, "
                            f"user B (different identity, same request) also got "
                            f"HTTP {resp_b.status_code}."
                        ),
                    )
                ]
            # resp_b was 3xx/4xx (e.g. 403/404) for this id -> looks properly
            # enforced for this candidate; keep trying other ids rather than
            # concluding the endpoint is safe from one sample.
        return []


def _has_id_path_param(path: str) -> bool:
    return "{" in path and "}" in path
